let songs=[
  {
    name:'Charlie_Pularikalol',
    path:'Charlie_Pularikalol.mp3',
    cover:''
  },
  {
    name:'Ethu_Kari_Raavilum',
    path:'Ethu_Kari_Raavilum.mp3',
    cover:''
  },
  {
    name:'Gasolina',
    path:'Gasolina.mp3',
    cover:''
  },
  {
    name:'Hey_Nimal',
    path:'Hey_Nimal.mp3',
    cover:''
  },
  {
    name:'Jeevamshamayi',
    path:'Jeevamshamayi.mp3',
    cover:''
  },
  {
    name:'Kalamanodishtam',
    path:'Kalamanodishtam.mp3',
    cover:''
  },
  {
    name:'Kando_kando',
    path:'Kando_kando.mp3',
    cover:''
  },
  {
    name:'Kangal_Neeye',
    path:'Kangal_Neeye.mp3',
    cover:''
  },
  {
    name:'koode_Thullu',
    path:'koode_Thullu.mp3',
    cover:''
  },
  {
    name:'Kotha_Raja',
    path:'Kotha_Raja.mp3',
    cover:''
  },
  {
    name:'Lokiverse',
    path:'Lokiverse.mp3',
    cover:''
  },
{
    name:'Manuja',
    path:'Manuja.mp3',
    cover:''
  },
  {
    name:'Mazhanila',
    path:'Mazhanila.mp3',
    cover:''
  },
  {
    name:'Nenjame_Nenajame',
    path:'Nenjame_Nenajame.mp3',
    cover:''
  },
  {
    name:'Olam_Up',
    path:'Olam_Up.mp3',
    cover:''
  },
  {
    name:'OLLULLERU',
    path:'OLLULLERU.mp3',
    cover:''
  },
  {
    name:'Perilla_Raajyathe',
    path:'Perilla_Raajyathe.mp3',
    cover:''
  },
  {
    name:'Ram_Chahe_Leela',
    path:'Ram_Chahe_Leela.mp3',
    cover:''
  },
  {
    name:'Thalatherichavar',
    path:'Thalatherichavar.mp3',
    cover:''
  },
  {
    name:'The_Hymn_Of_Dharma',
    path:'The_Hymn_Of_Dharma.mp3',
    cover:''
  },
    {
    name:'Thiru_Thiru_Thiruvananthapurathu',
    path:'Thiru_Thiru_Thiruvananthapurathu.mp3',
    cover:''
  },
  {
    name:'Tip_Tip',
    path:'Tip_Tip.mp3',
    cover:''
  }
]